import { randomUUID } from "node:crypto";
import type { ResolvedConfig } from "../config/index.js";
import { BrokerArgumentError, BrokerError } from "../errors/index.js";
import { keys } from "../redis/keys.js";
import { sweepExpiredReservations } from "./cleanup.js";
import { defineScript, runScript } from "../redis/script.js";
import { fireHook } from "../hooks/fire.js";
import { isRedisUnavailableError } from "../redis/unavailable.js";

export interface RequestPermissionInput {
  agentId: string;
  target: string;
  estimatedCost: number;
  ttl?: number;
}
export interface Admitted {
  allowed: true;
  reservationId: string | null;
  retryAfter?: number;
  /** True only when this admission bypassed all coordination because Redis was unreachable
   * and onRedisUnavailable is 'allow'. budget, concurrency, and circuit state were neither
   * checked nor updated. reservationId is null in this case — see reportOutcome's handling
   * of a null reservationId, which is a defined, safe no-op specifically for this case. */
  degraded?: boolean;
}
export type DenialReason = "unknown_agent" | "budget_exceeded" | "concurrency_exceeded" | "circuit_open" | "redis_unavailable" | "queue_timeout";
export interface Denied {
  allowed: false;
  reason: DenialReason;
}

// Grace period beyond the caller's TTL before the reservation hash is physically deleted.
// The sorted-set score (expiresAt), not this Redis-level TTL, is what decides logical expiry;
// the grace period only keeps the hash's fields alive long enough for lazy cleanup to read them.
const RESERVATION_GRACE_MS = 5_000;

/**
 * KEYS[1] agent hash               KEYS[2] budget pool (integer)
 * KEYS[3] new reservation hash     KEYS[4] expiring-reservations sorted set
 * KEYS[5] concurrency counter (integer, per target+budgetKey)
 * KEYS[6] circuit failure window (sorted set, per target)
 * KEYS[7] circuit state (string, per target)
 *
 * ARGV[1] agentId  ARGV[2] estimatedCost  ARGV[3] target  ARGV[4] ttl (ms)
 * ARGV[5] now (ms)  ARGV[6] reservationId  ARGV[7] agentTtl (ms)
 * ARGV[8] budgetKey  ARGV[9] grace (ms)  ARGV[10] concurrencyLimit
 * ARGV[11] windowMs  ARGV[12] softThreshold  ARGV[13] hardThreshold
 * ARGV[14] probeRate  ARGV[15] random draw in [0,1), generated by the caller (TypeScript side)
 *
 * The caller already read the agent's budgetKey (immutable per ADR-20, so a separate read is
 * safe) to build KEYS[2] and KEYS[5] — Lua cannot compute a key name from data it reads
 * mid-script. This script re-checks agent *existence* itself: that is the part that can change
 * between the caller's earlier read and now (Section 11, race #4), not the budgetKey value.
 *
 * Checked in this order, closing ADR-18 (budget, concurrency, and circuit breaker all converge
 * into one atomic script): agent existence, circuit state, budget, concurrency.
 *
 * Circuit comes right after existence and before budget/concurrency: if a target is
 * circuit-open, there is no point reserving budget or a concurrency slot for a call we are
 * about to deny anyway — except for the one probe call per the probe draw, which is admitted
 * normally through the same budget/concurrency checks as everything else (a probe is a real
 * call, not a dry run).
 *
 * The failure count is read fresh every admission (trim via ZREMRANGEBYSCORE, then ZCARD),
 * not cached, trading one extra Redis op per call for correctness — the window is already
 * bounded in size by the trim. count >= hardThreshold flips state to 'open' the first time
 * it's observed and denies. count >= softThreshold (but below hard) admits normally but
 * attaches retryAfter as backpressure. state == 'open' is checked before the fresh count,
 * since a long-open circuit's window may have aged below hardThreshold without a successful
 * probe ever confirming recovery — recovery is a probe-success event (handled in
 * reportOutcome), not a count-drops-back-down event. This is a deliberate design choice:
 * conflating the two would let an untested target silently reopen from wall-clock time alone.
 *
 * Budget check-and-reserve is one atomic step (race #1): two concurrent calls could otherwise
 * both read "enough budget" before either decrements, and both admit. A missing pool reads as
 * balance 0, so an unfunded budgetKey denies exactly like an empty one.
 *
 * Concurrency closes the equivalent race for Invariant 13 (scoped per target+budgetKey, never
 * leaking across unrelated pairs — see keys.ts). Checked after budget: budget exhaustion
 * (Invariant 5) is the stronger guarantee and should surface first when both would fail.
 *
 * budgetKey is written onto the reservation hash (not just derivable via the agent) so that
 * reconciliation (reportOutcome) can refund the right pool even if the agent record has since
 * expired — the reservation must outlive its own agent. isProbe is stamped here so
 * reportOutcome can tell a probe reservation apart from an ordinary one without extra state.
 *
 * Nothing is written on any denial path.
 */
const REQUEST_PERMISSION = defineScript(
  `
if redis.call('EXISTS', KEYS[1]) == 0 then
  return {0, 'unknown_agent'}
end

local windowMs = tonumber(ARGV[11])
redis.call('ZREMRANGEBYSCORE', KEYS[6], '-inf', tonumber(ARGV[5]) - windowMs)
local failureCount = redis.call('ZCARD', KEYS[6])
local softThreshold = tonumber(ARGV[12])
local hardThreshold = tonumber(ARGV[13])
local state = redis.call('GET', KEYS[7])

local isProbe = false
local justOpened = false

if state == 'open' then
  if tonumber(ARGV[15]) < tonumber(ARGV[14]) then
    isProbe = true
  else
    return {0, 'circuit_open'}
  end
elseif failureCount >= hardThreshold then
  redis.call('SET', KEYS[7], 'open')
  justOpened = true
  return {0, 'circuit_open', '1'}
end

local cost = tonumber(ARGV[2])
local balanceRaw = redis.call('GET', KEYS[2])
local balance = balanceRaw and tonumber(balanceRaw) or 0
if balance < cost then
  return {0, 'budget_exceeded'}
end

local limit = tonumber(ARGV[10])
local inFlightRaw = redis.call('GET', KEYS[5])
local inFlight = inFlightRaw and tonumber(inFlightRaw) or 0
if inFlight >= limit then
  return {0, 'concurrency_exceeded'}
end

redis.call('DECRBY', KEYS[2], cost)
redis.call('INCR', KEYS[5])
redis.call('HSET', KEYS[3],
  'agentId', ARGV[1], 'budgetKey', ARGV[8], 'target', ARGV[3],
  'estimatedCost', cost, 'createdAt', ARGV[5], 'isProbe', isProbe and '1' or '0')
redis.call('PEXPIRE', KEYS[3], tonumber(ARGV[4]) + tonumber(ARGV[9]))
redis.call('ZADD', KEYS[4], tonumber(ARGV[5]) + tonumber(ARGV[4]), ARGV[6])
redis.call('HSET', KEYS[1], 'lastHeartbeat', ARGV[5])
redis.call('PEXPIRE', KEYS[1], tonumber(ARGV[7]))

if failureCount >= softThreshold and failureCount < hardThreshold then
  local retryAfter = math.floor(windowMs / (hardThreshold - softThreshold + 1))
  return {1, retryAfter}
end
return {1}
`,
  7,
);

function validate(input: unknown): asserts input is RequestPermissionInput {
  if (input === null || typeof input !== "object") {
    throw new BrokerArgumentError("requestPermission() expects an options object");
  }
  const allowed = new Set(["agentId", "target", "estimatedCost", "ttl"]);
  for (const field of Object.keys(input)) {
    if (!allowed.has(field)) throw new BrokerArgumentError(`requestPermission() does not accept "${field}"`);
  }
  const { agentId, target, estimatedCost, ttl } = input as Record<string, unknown>;
  if (typeof agentId !== "string" || agentId.length === 0) {
    throw new BrokerArgumentError("agentId must be a non-empty string");
  }
  if (typeof target !== "string" || target.length === 0) {
    throw new BrokerArgumentError("target must be a non-empty string");
  }
  if (!Number.isSafeInteger(estimatedCost) || (estimatedCost as number) <= 0) {
    throw new BrokerArgumentError(`estimatedCost must be a positive integer, got ${String(estimatedCost)}`);
  }
  if (ttl !== undefined && (!Number.isSafeInteger(ttl) || (ttl as number) <= 0)) {
    throw new BrokerArgumentError(`ttl must be a positive integer (ms), got ${String(ttl)}`);
  }
}
export async function requestPermission(
  config: ResolvedConfig,
  input: RequestPermissionInput,
): Promise<Admitted | Denied> {
  validate(input);

  const ttl = input.ttl ?? config.defaultReservationTtl;
  if (ttl > config.maxReservationTtl) {
    throw new BrokerArgumentError(
      `ttl (${ttl}ms) exceeds maxReservationTtl (${config.maxReservationTtl}ms) configured for this broker`,
    );
  }

  try {
    await sweepExpiredReservations(config);

      const budgetKey = await config.redis.hget(keys.agent(input.agentId), "budgetKey");
      if (budgetKey === null) {
        const result: Denied = { allowed: false, reason: "unknown_agent" };
    fireHook(config.hooks.onDecision, { agentId: input.agentId, target: input.target, result });
    return result;
  }

    const reservationId = randomUUID();
    const cb = config.circuitBreaker;
    const reply = await runScript(
      config.redis,
      REQUEST_PERMISSION,
      [
        keys.agent(input.agentId),
        keys.budget(budgetKey),
        keys.reservation(reservationId),
        keys.reservationsExpiring(),
        keys.concurrency(input.target, budgetKey),
        keys.circuit(input.target),
        keys.circuitState(input.target),
      ],
      [
        input.agentId, input.estimatedCost, input.target, ttl, Date.now(), reservationId,
        config.agentTtl, budgetKey, RESERVATION_GRACE_MS, config.concurrencyLimit,
        cb.windowMs, cb.softThreshold, cb.hardThreshold, cb.probeRate, Math.random(),
      ],
    );

     if (Array.isArray(reply)) {
    const [status, a, b] = reply as unknown[];
    if (status === 0) {
      const reason = a as DenialReason;
      if (reason === "circuit_open" && b === "1") {
        fireHook(config.hooks.onCircuitStateChange, { target: input.target, state: "open" });
      }
      if (reason === "unknown_agent" || reason === "budget_exceeded" || reason === "concurrency_exceeded" || reason === "circuit_open") {
        const result: Denied = { allowed: false, reason };
        fireHook(config.hooks.onDecision, { agentId: input.agentId, target: input.target, result });
        return result;
      }
    }
    if (status === 1) {
      const result: Admitted = a === undefined
        ? { allowed: true, reservationId }
        : { allowed: true, reservationId, retryAfter: a as number };
      fireHook(config.hooks.onDecision, { agentId: input.agentId, target: input.target, result });
      return result;
    }
  }
    throw new BrokerError(`unexpected reply from request-permission script: ${JSON.stringify(reply)}`);
    } catch (error) {
    if (!isRedisUnavailableError(error)) throw error;

    const result: Admitted | Denied = config.onRedisUnavailable === "allow"
      ? { allowed: true, reservationId: null, degraded: true }
      : { allowed: false, reason: "redis_unavailable" };
    fireHook(config.hooks.onDecision, { agentId: input.agentId, target: input.target, result });
    return result;
  }
}